# This file is part of our engineering process to build and maintain this file.
# See the README markdown file for further details

name: "RWA: Scheduled Teardown"

on:
  pull_request:
      types:
      - closed
  workflow_dispatch:
    inputs:
      environment:
        description: 'App environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
      run_azd_tear_down:
        description: 'When true, AZD resources will be deleted'
        required: false
        default: true
        type: boolean
  
  schedule:
    - cron: '0 13,15 * * *'

# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

concurrency: integration_testing

env:
  APP_NAME: ${{ vars.AZURE_APP_NAME }}
  APP_ENVIRONMENT: ${{ inputs.environment || 'dev' }}
  AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Install the az cli with login using service principal created on az subscription
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: print input env variables
      run: |
        echo $APP_NAME
        echo $AZURE_LOCATION

    - name: Install jq tool
      run: |
        sudo apt-get update
        sudo apt-get install jq

    - name: Delete Resource Groups
      if: ${{ inputs.run_azd_tear_down || github.event_name == 'schedule' }}
      run: |
        ./scripts/devOpsScripts/delete-resources.sh --application-name $APP_NAME --location $AZURE_LOCATION