# This file is part of our engineering process to build and maintain this file.
# See the README markdown file for further details

name: "RWA: Scheduled Teardown"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'App environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
  
  schedule:
    - cron: '0 13 * * *'

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    steps:

      - name: Set default environment value
        run: |
          echo "::set-output name=value::${{ github.event.inputs.environment || 'dev' }}"

      - name: Checkout
        uses: actions/checkout@v2

      # Install the az cli with login using service principal created on az subscription
      - name: 'azure cli'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'delete-resources'
        run: |
          chmod +x ./scripts/devOpsScripts/delete-resources.sh
          ./scripts/devOpsScripts/delete-resources.sh -g rg-${{ secrets.AZURE_APP_NAME }}-${{ inputs.environment }}